server:
  port: 8800

spring:
  # dev|pro
  profiles:
    active: pro
  #  datasource:
  #      url: jdbc:mysql://localhost:3306/erupt?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
  #      username: root
  #      password: 123456
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      hikari:
  #        # 连接池最大连接数
  #        maximum-pool-size: 12
  #        # 空闲时保持最小连接数
  #        minimum-idle: 5
  #        # 空闲连接存活时间
  #        idle-timeout: 300000
  #        # 连接超时时间
  #        connection-timeout: 20000
  #        # 测试sql
  #        connection-test-query: select 1

  application:
    name: home
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-idle: 8 # 连接池中的最大空闲连接默认 8
        min-idle: 0 # 连接池中的最小空闲连接默认 0
  servlet:
    multipart:
      max-file-size: 1024000
      max-request-size: 1024000
  jpa:
    generate-ddl: true
  #  静态资源加载配置
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
